# Generated by Django 5.2 on 2025-06-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sectores',
            field=models.ManyToManyField(blank=True, related_name='supervisores', to='core.sector'),
        ),
    ]
