# Generated by Django 5.2 on 2025-10-08 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_sectores'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePredio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sector', models.CharField(blank=True, default='', max_length=50)),
                ('codigo_predio', models.CharField(blank=True, default='', max_length=50)),
                ('via_acceso', models.CharField(blank=True, default='', max_length=100)),
                ('numero_municipal', models.CharField(blank=True, default='', max_length=50)),
                ('terreno', models.CharField(blank=True, default='', max_length=50)),
                ('denominacion', models.CharField(blank=True, default='-', max_length=100)),
                ('comercio', models.IntegerField(default=0)),
                ('vivienda', models.IntegerField(default=0)),
                ('homepass', models.IntegerField(default=0)),
                ('esquina', models.BooleanField(default=False)),
                ('actividad', models.CharField(blank=True, default='ND', max_length=100)),
                ('nombre_institucion', models.CharField(blank=True, default='-', max_length=150)),
                ('estado_registro', models.CharField(choices=[('registrado', 'Registrado'), ('observado', 'Observado'), ('pendiente', 'Pendiente')], default='registrado', max_length=20)),
                ('reporte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_predio', to='core.reporte')),
            ],
        ),
    ]
