# Generated by Django 5.2 on 2025-10-08 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_sector_zona_distrito_zona_distrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zona',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.proyecto'),
        ),
    ]
