# Generated by Django 5.2 on 2025-10-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_zona_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepredio',
            name='caracteristicas_predio_tipo',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='detallepredio',
            name='centro_poblado',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='detallepredio',
            name='lote',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detallepredio',
            name='manzana',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='detallepredio',
            name='nombre_via_acceso',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='detallepredio',
            name='urbanizacion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='detallepredio',
            name='actividad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detallepredio',
            name='codigo_predio',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='detallepredio',
            name='denominacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detallepredio',
            name='nombre_institucion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
