# Generated by Django 5.2 on 2025-10-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_detallepredio_caracteristicas_predio_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='tipo',
            field=models.CharField(choices=[('electrico', 'Poste Eléctrico'), ('telematico', 'Poste Telemático'), ('predio', 'Predio')], max_length=20),
        ),
    ]
