# Generated by Django 5.2 on 2025-10-09 22:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_reporte_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredioWizard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detalle_payload', models.JSONField(blank=True, null=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('coords_captured_at', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('started', 'Iniciado'), ('in_progress', 'En progreso'), ('ready', 'Listo para publicar'), ('published', 'Publicado'), ('expired', 'Expirado')], default='started', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.distrito')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sector')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.zona')),
            ],
        ),
    ]
