# Generated by Django 5.2 on 2025-10-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_prediowizard'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotoreporte',
            name='is_principal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prediowizard',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prediowizard',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='fotoreporte',
            name='tipo',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='prediowizard',
            name='detalle_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('registrado', 'Registrado'), ('observado', 'Observado')], default='pendiente', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='fotoreporte',
            constraint=models.UniqueConstraint(condition=models.Q(('is_principal', True)), fields=('reporte',), name='uniq_foto_principal_por_reporte'),
        ),
    ]
