# Generated by Django 5.2 on 2025-10-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_fotoreporte_is_principal_prediowizard_is_published_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elementoelectrico',
            options={'ordering': ['tipo', 'nombre']},
        ),
        migrations.AddField(
            model_name='elementoelectrico',
            name='tipo',
            field=models.CharField(choices=[('electrico', 'Eléctrico'), ('telematico', 'Telemático')], default='electrico', max_length=10),
        ),
        migrations.AlterField(
            model_name='elementoelectrico',
            name='nombre',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterModelTable(
            name='elementoelectrico',
            table='elementos',
        ),
    ]
