# Generated by Django 5.2 on 2025-10-13 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_elementoelectrico_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementoelectrico',
            name='tipo',
            field=models.CharField(choices=[('electrico', 'Eléctrico'), ('telematico', 'Telemático')], max_length=10),
        ),
        migrations.CreateModel(
            name='PosteElectricoWizard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tension', models.CharField(blank=True, choices=[('BT', 'Baja Tensión'), ('MT', 'Media Tensión'), ('AT', 'Alta Tensión')], max_length=2, null=True)),
                ('cables_electricos', models.PositiveIntegerField(blank=True, null=True)),
                ('cables_telematicos', models.PositiveIntegerField(blank=True, null=True)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('elementos_electricos', models.JSONField(blank=True, default=list)),
                ('elementos_telematicos', models.JSONField(blank=True, default=list)),
                ('estado', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado')], default='draft', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poste_wizards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-actualizado_en'],
                'indexes': [models.Index(fields=['encargado', 'estado'], name='core_postee_encarga_c3a97e_idx')],
            },
        ),
    ]
