# Generated by Django 5.2 on 2025-10-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_elementoelectrico_tipo_posteelectricowizard'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('estructura', 'Estructura'), ('material', 'Material'), ('zona_instalacion', 'Zona de instalación'), ('resistencia', 'Resistencia')], db_index=True, max_length=32)),
                ('nombre', models.CharField(max_length=64)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'parametros_catalogo',
                'ordering': ['categoria', 'orden', 'nombre'],
                'unique_together': {('categoria', 'nombre')},
            },
        ),
    ]
