# Generated by Django 5.2 on 2025-10-13 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_parametrocatalogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosteElectricoWizard_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('resistencia_valor', models.PositiveIntegerField(blank=True, null=True)),
                ('coordenadas', models.JSONField(blank=True, default=dict)),
                ('estructura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='w2_estructura', to='core.parametrocatalogo')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='w2_material', to='core.parametrocatalogo')),
                ('resistencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='w2_resistencia', to='core.parametrocatalogo')),
                ('wizard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas', to='core.posteelectricowizard')),
                ('zona_instalacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='w2_zona', to='core.parametrocatalogo')),
            ],
            options={
                'ordering': ['-actualizado_en'],
            },
        ),
    ]
