# Generated by Django 5.2 on 2025-10-13 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_posteelectricowizard_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosteElectricoWizard_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_poste', models.CharField(blank=True, max_length=64, null=True)),
                ('inclinacion', models.CharField(blank=True, max_length=64, null=True)),
                ('propietario', models.CharField(blank=True, max_length=16, null=True)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('wizard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='condicion', to='core.posteelectricowizard')),
            ],
            options={
                'ordering': ['-actualizado_en'],
            },
        ),
    ]
