# Generated by Django 5.2 on 2025-10-14 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_posteelectricowizard_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteelectricowizard_3',
            name='estado_poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.estadofisico'),
        ),
        migrations.AlterField(
            model_name='posteelectricowizard_3',
            name='inclinacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.inclinacion'),
        ),
        migrations.AlterField(
            model_name='posteelectricowizard_3',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.propietario'),
        ),
    ]
