# Generated by Django 5.2 on 2025-10-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_posteelectricowizard_3_estado_poste_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteelectricowizard_3',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
