# Generated by Django 5.2 on 2025-10-17 17:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_posteelectricowizard_3_altura'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosteElectricoWizard_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('wizard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ubicacion', to='core.posteelectricowizard')),
            ],
            options={
                'verbose_name': 'Ubicación y Observaciones de Poste',
                'verbose_name_plural': 'Ubicaciones y Observaciones de Postes',
                'ordering': ['-actualizado_en'],
            },
        ),
        migrations.CreateModel(
            name='FotoPosteWizard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(help_text='Foto del poste eléctrico', upload_to='fotos_postes/%Y/%m/')),
                ('orden', models.PositiveSmallIntegerField(default=1, help_text='Orden de la foto (1-6)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('wizard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.posteelectricowizard')),
            ],
            options={
                'verbose_name': 'Foto de Poste',
                'verbose_name_plural': 'Fotos de Postes',
                'ordering': ['wizard', 'orden'],
                'unique_together': {('wizard', 'orden')},
            },
        ),
    ]
