# Generated by Django 5.2 on 2025-10-17 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_posteelectricowizard_4_fotopostewizard'),
    ]

    operations = [
    ]
