# Generated by Django 5.2 on 2025-10-18 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20251017_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosteTelematicWizard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cables_telematicos', models.PositiveIntegerField(blank=True, null=True)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('cable_electrico', models.PositiveIntegerField(blank=True, null=True)),
                ('elementos_telematicos', models.JSONField(blank=True, default=list)),
                ('elementos_electricos', models.JSONField(blank=True, default=list)),
                ('estado', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado')], default='draft', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poste_telematico_wizards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-actualizado_en'],
                'indexes': [models.Index(fields=['encargado', 'estado'], name='core_postet_encarga_f3befc_idx')],
            },
        ),
    ]
