# Generated by Django 5.2 on 2025-10-18 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_postetelematicwizard'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosteTelematicWizard_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resistencia_valor', models.PositiveIntegerField(blank=True, null=True)),
                ('coordenadas', models.JSONField(blank=True, default=dict)),
                ('cables_telematicos', models.PositiveIntegerField(blank=True, null=True)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('cable_electrico', models.PositiveIntegerField(blank=True, null=True)),
                ('elementos_telematicos', models.JSONField(blank=True, default=list)),
                ('elementos_electricos', models.JSONField(blank=True, default=list)),
                ('estado', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado')], default='draft', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-actualizado_en'],
            },
        ),
        migrations.AlterModelOptions(
            name='postetelematicwizard',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='postetelematicwizard',
            name='core_postet_encarga_f3befc_idx',
        ),
        migrations.RemoveField(
            model_name='postetelematicwizard',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='postetelematicwizard',
            name='cable_electrico',
        ),
        migrations.RemoveField(
            model_name='postetelematicwizard',
            name='cables_telematicos',
        ),
        migrations.RemoveField(
            model_name='postetelematicwizard',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='postetelematicwizard',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='postetelematicwizard',
            name='elementos_electricos',
        ),
        migrations.RemoveField(
            model_name='postetelematicwizard',
            name='elementos_telematicos',
        ),
        migrations.RemoveField(
            model_name='postetelematicwizard',
            name='encargado',
        ),
        migrations.RemoveField(
            model_name='postetelematicwizard',
            name='estado',
        ),
        migrations.AddField(
            model_name='postetelematicwizard_2',
            name='encargado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poste_telematico_wizards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postetelematicwizard_2',
            name='estructura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='telematico_estructura', to='core.parametrocatalogo'),
        ),
        migrations.AddField(
            model_name='postetelematicwizard_2',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='telematico_material', to='core.parametrocatalogo'),
        ),
        migrations.AddField(
            model_name='postetelematicwizard_2',
            name='resistencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='telematico_resistencia', to='core.parametrocatalogo'),
        ),
        migrations.AddField(
            model_name='postetelematicwizard_2',
            name='wizard',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas', to='core.postetelematicwizard'),
        ),
        migrations.AddField(
            model_name='postetelematicwizard_2',
            name='zona_instalacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='telematico_zona', to='core.parametrocatalogo'),
        ),
        migrations.AddIndex(
            model_name='postetelematicwizard_2',
            index=models.Index(fields=['encargado', 'estado'], name='core_postet_encarga_5d53f4_idx'),
        ),
    ]
