# Generated by Django 5.2 on 2025-10-18 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_postetelematicwizard_2_and_more'),
    ]

    operations = [
    ]
