# Generated by Django 5.2 on 2025-10-19 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20251018_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoTelematicWizard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='telematicos/fotos/')),
                ('descripcion', models.CharField(blank=True, max_length=100)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('is_principal', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Foto de Poste Telemático',
                'verbose_name_plural': 'Fotos de Postes Telemáticos',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='PosteTelematicWizard_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notas', models.TextField(blank=True)),
                ('resistencia_valor', models.PositiveIntegerField(blank=True, null=True)),
                ('coordenadas', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Características de Poste Telemático',
                'verbose_name_plural': 'Características de Postes Telemáticos',
                'ordering': ['-actualizado_en'],
            },
        ),
        migrations.CreateModel(
            name='PosteTelematicWizard_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=8, max_digits=10, null=True)),
                ('longitud', models.DecimalField(decimal_places=8, max_digits=11, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ubicación de Poste Telemático',
                'verbose_name_plural': 'Ubicaciones de Postes Telemáticos',
                'ordering': ['-actualizado_en'],
            },
        ),
        migrations.AlterModelOptions(
            name='postetelematicwizard',
            options={'ordering': ['-actualizado_en']},
        ),
        migrations.AlterModelOptions(
            name='postetelematicwizard_2',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='postetelematicwizard_2',
            name='core_postet_encarga_5d53f4_idx',
        ),
        migrations.RemoveField(
            model_name='postetelematicwizard_2',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='postetelematicwizard_2',
            name='cable_electrico',
        ),
        migrations.RemoveField(
            model_name='postetelematicwizard_2',
            name='cables_telematicos',
        ),
        migrations.RemoveField(
            model_name='postetelematicwizard_2',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='postetelematicwizard_2',
            name='coordenadas',
        ),
        migrations.RemoveField(
            model_name='postetelematicwizard_2',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='postetelematicwizard_2',
            name='elementos_electricos',
        ),
        migrations.RemoveField(
            model_name='postetelematicwizard_2',
            name='elementos_telematicos',
        ),
        migrations.RemoveField(
            model_name='postetelematicwizard_2',
            name='encargado',
        ),
        migrations.RemoveField(
            model_name='postetelematicwizard_2',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='postetelematicwizard_2',
            name='estructura',
        ),
        migrations.RemoveField(
            model_name='postetelematicwizard_2',
            name='material',
        ),
        migrations.RemoveField(
            model_name='postetelematicwizard_2',
            name='resistencia',
        ),
        migrations.RemoveField(
            model_name='postetelematicwizard_2',
            name='resistencia_valor',
        ),
        migrations.RemoveField(
            model_name='postetelematicwizard_2',
            name='wizard',
        ),
        migrations.RemoveField(
            model_name='postetelematicwizard_2',
            name='zona_instalacion',
        ),
        migrations.AddField(
            model_name='postetelematicwizard',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='postetelematicwizard',
            name='cable_electrico',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postetelematicwizard',
            name='cables_telematicos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postetelematicwizard',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='postetelematicwizard',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='postetelematicwizard',
            name='elementos_electricos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='postetelematicwizard',
            name='elementos_telematicos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='postetelematicwizard',
            name='encargado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poste_telematico_wizard_principal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postetelematicwizard',
            name='estado',
            field=models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado')], default='draft', max_length=10),
        ),
        migrations.AddIndex(
            model_name='postetelematicwizard',
            index=models.Index(fields=['encargado', 'estado'], name='core_postet_encarga_f3befc_idx'),
        ),
        migrations.AddField(
            model_name='postetelematicwizard_3',
            name='estado_poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.estadofisico'),
        ),
        migrations.AddField(
            model_name='postetelematicwizard_3',
            name='estructura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='telematico_estructura', to='core.parametrocatalogo'),
        ),
        migrations.AddField(
            model_name='postetelematicwizard_3',
            name='inclinacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.inclinacion'),
        ),
        migrations.AddField(
            model_name='postetelematicwizard_3',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='telematico_material', to='core.parametrocatalogo'),
        ),
        migrations.AddField(
            model_name='postetelematicwizard_3',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.propietario'),
        ),
        migrations.AddField(
            model_name='postetelematicwizard_3',
            name='resistencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='telematico_resistencia', to='core.parametrocatalogo'),
        ),
        migrations.AddField(
            model_name='postetelematicwizard_3',
            name='wizard',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas', to='core.postetelematicwizard'),
        ),
        migrations.AddField(
            model_name='postetelematicwizard_3',
            name='zona_instalacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='telematico_zona', to='core.parametrocatalogo'),
        ),
        migrations.AddField(
            model_name='postetelematicwizard_4',
            name='wizard',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ubicacion', to='core.postetelematicwizard'),
        ),
        migrations.AddField(
            model_name='fototelematicwizard',
            name='wizard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.postetelematicwizard_4'),
        ),
    ]
