# Generated by Django 4.2 on 2025-10-19 02:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_fototelematicwizard_postetelematicwizard_3_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postetelematicwizard_2',
            options={'ordering': ['-actualizado_en'], 'verbose_name': 'Características de Poste Telemático', 'verbose_name_plural': 'Características de Postes Telemáticos'},
        ),
        migrations.AlterModelOptions(
            name='postetelematicwizard_3',
            options={'ordering': ['-actualizado_en'], 'verbose_name': 'Condición de Poste Telemático', 'verbose_name_plural': 'Condiciones de Postes Telemáticos'},
        ),
        migrations.RemoveField(
            model_name='postetelematicwizard_3',
            name='coordenadas',
        ),
        migrations.RemoveField(
            model_name='postetelematicwizard_3',
            name='estructura',
        ),
        migrations.RemoveField(
            model_name='postetelematicwizard_3',
            name='material',
        ),
        migrations.RemoveField(
            model_name='postetelematicwizard_3',
            name='resistencia',
        ),
        migrations.RemoveField(
            model_name='postetelematicwizard_3',
            name='resistencia_valor',
        ),
        migrations.RemoveField(
            model_name='postetelematicwizard_3',
            name='zona_instalacion',
        ),
        migrations.AddField(
            model_name='postetelematicwizard_2',
            name='actualizado_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='postetelematicwizard_2',
            name='coordenadas',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='postetelematicwizard_2',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='postetelematicwizard_2',
            name='estructura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='telematico_estructura_parte2', to='core.parametrocatalogo'),
        ),
        migrations.AddField(
            model_name='postetelematicwizard_2',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='telematico_material_parte2', to='core.parametrocatalogo'),
        ),
        migrations.AddField(
            model_name='postetelematicwizard_2',
            name='resistencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='telematico_resistencia_parte2', to='core.parametrocatalogo'),
        ),
        migrations.AddField(
            model_name='postetelematicwizard_2',
            name='resistencia_valor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postetelematicwizard_2',
            name='wizard',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas_fisicas', to='core.postetelematicwizard'),
        ),
        migrations.AddField(
            model_name='postetelematicwizard_2',
            name='zona_instalacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='telematico_zona_parte2', to='core.parametrocatalogo'),
        ),
        migrations.AlterField(
            model_name='fototelematicwizard',
            name='actualizado_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='fototelematicwizard',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='postetelematicwizard',
            name='actualizado_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='postetelematicwizard',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='postetelematicwizard_3',
            name='actualizado_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='postetelematicwizard_3',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='postetelematicwizard_3',
            name='estado_poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='telematico_estados_parte3', to='core.estadofisico'),
        ),
        migrations.AlterField(
            model_name='postetelematicwizard_3',
            name='inclinacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='telematico_inclinaciones_parte3', to='core.inclinacion'),
        ),
        migrations.AlterField(
            model_name='postetelematicwizard_3',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='telematico_propietarios_parte3', to='core.propietario'),
        ),
        migrations.AlterField(
            model_name='postetelematicwizard_3',
            name='wizard',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condiciones_tecnicas', to='core.postetelematicwizard'),
        ),
        migrations.AlterField(
            model_name='postetelematicwizard_4',
            name='actualizado_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='postetelematicwizard_4',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
